### ISSUE TITLE
How does it works?

### ISSUE THREAD

**Issue by PaoloOcchioniLynx** [kritarthu/watchmen-ping-http-contains-headers#1]
Hello
I've Installed it and I can see the name in dropdown Ping Service, but how can I pass the headers?
Bye

**Comment by kritarthu** [comment]
@PaoloOcchioniLynx  Hello, you can use a JSON to pass all the headers.
Like:
{"SVC.NAME":"xyz","VERSION":"0.91.8","Content-Type":"application/json"}

**Comment by PaoloOcchioniLynx** [comment]
Hello
I was able to successfully pass the headers, but the plugin was not working.
I had to replace 'http-contains-post' with 'http-contains-headers' in index.js from line 21 to 30.
Thanks

**Comment by kritarthu** [comment]
@PaoloOcchioniLynx, Yes headers will only be passed with the plugins having "headers" in the name. Thanks! Closing the issue.
